/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pthak
 */
public class RenterProfile extends javax.swing.JFrame {

    /**
     * Creates new form RenterProfile
     */
    public RenterProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        renterBooking = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        viewListings = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        listField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        bookButton = new javax.swing.JButton();
        tableDisplay8 = new javax.swing.JScrollPane();
        renterTable = new javax.swing.JTable();
        jField12 = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        userPassword = new javax.swing.JPasswordField();
        successField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        userIdField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        listingField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bookDate = new javax.swing.JTextField();
        viewListingsCurrent = new javax.swing.JButton();
        cancelBooking = new javax.swing.JButton();
        tableDisplay9 = new javax.swing.JScrollPane();
        viewBookingTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        bookingPassword = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        userComment = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        hostComment = new javax.swing.JTextField();
        userPassComment = new javax.swing.JPasswordField();
        commentHost = new javax.swing.JButton();
        tableDisplay10 = new javax.swing.JScrollPane();
        viewTableComment = new javax.swing.JTable();
        commentField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        tableDisplay11 = new javax.swing.JScrollPane();
        viewBookingTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        listingUserId = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        commentListPassword = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        commentListId = new javax.swing.JTextField();
        viewCommentListings = new javax.swing.JButton();
        addListingComment = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        listingComment = new javax.swing.JTextField();
        listingRating = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        renterBooking.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        viewListings.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewListings.setText("View all listings");
        viewListings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewListingsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("List id:");

        listField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Date:");

        dateField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        bookButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bookButton.setText("Book now!");
        bookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonActionPerformed(evt);
            }
        });

        renterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "List id", "Name", "City", "Postal Code", "Country", "Description", "Lat", "Long", "Amenities", "Rent", "Dates"
            }
        ));
        tableDisplay8.setViewportView(renterTable);
        if (renterTable.getColumnModel().getColumnCount() > 0) {
            renterTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jField12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jField12.setText("User id:");

        userField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Password:");

        successField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        successField.setForeground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableDisplay8, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(viewListings)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jField12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(bookButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(successField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewListings)
                    .addComponent(jLabel1)
                    .addComponent(listField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookButton)
                    .addComponent(jField12)
                    .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(successField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(tableDisplay8, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        renterBooking.addTab("Renter booking", jPanel1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("user id:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Listing id:");

        listingField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Booking date:");

        bookDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        viewListingsCurrent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewListingsCurrent.setText("view current listings");
        viewListingsCurrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewListingsCurrentActionPerformed(evt);
            }
        });

        cancelBooking.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelBooking.setText("Cancel booking");
        cancelBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBookingActionPerformed(evt);
            }
        });

        viewBookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "User id", "Booking date", "List id", "Cancelled", "Host id"
            }
        ));
        tableDisplay9.setViewportView(viewBookingTable);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Password:");

        bookingPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableDisplay9, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bookingPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel4))
                            .addComponent(viewListingsCurrent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listingField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bookDate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBooking)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(viewListingsCurrent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(userIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(listingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(bookDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cancelBooking))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(bookingPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tableDisplay9, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        renterBooking.addTab("View/Cancel booking", jPanel2);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("User id:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Password:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Host id:");

        hostComment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        userPassComment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userPassComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPassCommentActionPerformed(evt);
            }
        });

        commentHost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        commentHost.setText("Add comment");
        commentHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentHostActionPerformed(evt);
            }
        });

        viewTableComment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User id", "Host id", "Place name", "Renting Date"
            }
        ));
        tableDisplay10.setViewportView(viewTableComment);
        if (viewTableComment.getColumnModel().getColumnCount() > 0) {
            viewTableComment.getColumnModel().getColumn(1).setHeaderValue("Cancelled");
        }

        commentField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        commentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentFieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Comment:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("View hosts");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tableDisplay10, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userComment))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(2, 2, 2)
                                .addComponent(userPassComment, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hostComment, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(commentField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(commentHost)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(userComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(hostComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userPassComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(commentHost))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(commentField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jButton1)))
                .addGap(29, 29, 29)
                .addComponent(tableDisplay10, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );

        renterBooking.addTab("Comment on hosts", jPanel3);

        viewBookingTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User id", "Renting date", "List id", "List Name"
            }
        ));
        tableDisplay11.setViewportView(viewBookingTable1);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("User id:");

        listingUserId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Password:");

        commentListPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("List id:");

        commentListId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        viewCommentListings.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewCommentListings.setText("View listings");
        viewCommentListings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCommentListingsActionPerformed(evt);
            }
        });

        addListingComment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addListingComment.setText("Add comment");
        addListingComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addListingCommentActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Comment:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Rating:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tableDisplay11))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(viewCommentListings)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listingUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13))
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(listingRating)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(commentListPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(commentListId, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(addListingComment))
                            .addComponent(listingComment, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 143, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(listingUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(commentListPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(commentListId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewCommentListings)
                    .addComponent(addListingComment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listingComment, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(listingRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(tableDisplay11, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        renterBooking.addTab("Comment on listing", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(renterBooking)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(renterBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listFieldActionPerformed

    private void viewListingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewListingsActionPerformed
        
        DefaultTableModel model ;
        model = (DefaultTableModel)renterTable.getModel();
        model.setRowCount(0);
        try {
            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            // setup connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/my_bnb?useSSL=false","root","rootpassword");
         
   
            PreparedStatement ps = conn.prepareStatement("SELECT * from listings L1,listing_dates L2 INNER JOIN listings ON listings.list_id = L2.listings_list_id");
            ResultSet rs = ps.executeQuery();
            System.out.println("listing search works");
            model.setRowCount(1);
            int rowIndex = 0;
            while (rs.next() && rowIndex < model.getRowCount()) {
 
                model.insertRow(rowIndex, 
                        new Object [] {rs.getString("list_id"),rs.getString("list_name"),
                            rs.getString("city"),rs.getString("postal_code"),rs.getString("country"),rs.getString("description"),rs.getString("latitude"),rs.getString("longitude"),rs.getString("amenities"),rs.getString("rent_amount"),rs.getString("dates")});
                rowIndex++;
            }
          
        } catch (SQLException e) {
            System.out.println("error");
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_viewListingsActionPerformed

    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonActionPerformed
        
        DefaultTableModel model ;
        model = (DefaultTableModel)renterTable.getModel();
        try {
            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            // setup connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/my_bnb?useSSL=false","root","rootpassword");
         
   
            PreparedStatement ps = conn.prepareStatement("INSERT INTO `bookings` (u_id,booking_date,listings_list_id,cancelled) VALUES (?,?,?,false)");
            ps.setString(1,userField.getText());
            ps.setString(2,dateField.getText());
            ps.setString(3,listField.getText());
            ps.executeUpdate();
            System.out.println("Booking worked!");
            
            PreparedStatement ps2 = conn.prepareStatement("DELETE FROM listing_dates WHERE dates = ? AND listings_list_id = ?");
            ps2.setString(1,dateField.getText());
            ps2.setString(2,listField.getText());
            ps2.executeUpdate();
            successField.setText("Success!");
 
        } catch (SQLException e) {
            System.out.println("error");
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_bookButtonActionPerformed

    private void viewListingsCurrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewListingsCurrentActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model ;
        model = (DefaultTableModel)viewBookingTable.getModel();
        try {
            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            // setup connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/my_bnb?useSSL=false","root","rootpassword");
         
   
            PreparedStatement ps = conn.prepareStatement("SELECT * from bookings WHERE u_id = ?");
            ps.setString(1,userIdField.getText());
            ResultSet rs = ps.executeQuery();
            System.out.println("listing search works");
            int rowIndex = 0;
            while (rs.next() && rowIndex < model.getRowCount()) {
 
                model.insertRow(rowIndex, 
                        new Object [] {rs.getString("u_id"),rs.getString("booking_date"),
                            rs.getString("listings_list_id"),rs.getString("cancelled"),rs.getString("hosts_id")});
                rowIndex++;
            }
          
        } catch (SQLException e) {
            System.out.println("error");
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_viewListingsCurrentActionPerformed

    private void cancelBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBookingActionPerformed
       
        DefaultTableModel model ;
        model = (DefaultTableModel)viewBookingTable.getModel();
        try {
            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            // setup connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/my_bnb?useSSL=false","root","rootpassword");
         
   
            PreparedStatement ps = conn.prepareStatement("SELECT * from bookings WHERE u_id = ?");
            ps.setString(1,userIdField.getText());
            ResultSet rs = ps.executeQuery();
            System.out.println("listing search works");
            int rowIndex = 0;
            while (rs.next() && rowIndex < model.getRowCount()) {
 
                model.insertRow(rowIndex, 
                        new Object [] {rs.getString("u_id"),rs.getString("booking_date"),
                            rs.getString("listings_list_id"),rs.getString("cancelled")});
                rowIndex++;
            }
          
        } catch (SQLException e) {
            System.out.println("error");
            System.err.println(e.getMessage());
        }
        
        
        
        
        
    }//GEN-LAST:event_cancelBookingActionPerformed

    private void userPassCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPassCommentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPassCommentActionPerformed

    private void commentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentFieldActionPerformed
        
        
                                               
    }//GEN-LAST:event_commentFieldActionPerformed

    private void commentHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentHostActionPerformed
        try {
            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            // setup connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/my_bnb?useSSL=false","root","rootpassword");
         
            // checks whether the renter has rented from the host before
            PreparedStatement ps = conn.prepareStatement("SELECT * from renter_has_listings INNER JOIN hosts_has_listings ON renter_has_listings.listings_list_id = hosts_has_listings.listings_list_id WHERE  hosts_has_listings.hosts_u_id=(?)");
            System.out.println("ioegigijerg");
            
            ps.setString(1,hostComment.getText());
            ResultSet rs = ps.executeQuery();
            
            // if renter rented from host then insert comment
            if (rs.next()) {
                System.out.println("found match");
                PreparedStatement addComment = conn.prepareStatement("INSERT INTO renter_comments (comment,commenter_id,commentee_id) VALUES (?,?,?)");
                addComment.setString(1,commentField.getText());
                addComment.setString(2,userComment.getText());
                addComment.setString(3,hostComment.getText());
                addComment.executeUpdate();
            }
            else{
                System.out.println("no found match");
            }
            
          
        } catch (SQLException e) {
            System.out.println("error");
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_commentHostActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model ;
        model = (DefaultTableModel)viewTableComment.getModel();
        model.setRowCount(0);
        try {
            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            // setup connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/my_bnb?useSSL=false","root","rootpassword");
         
   
            PreparedStatement ps = conn.prepareStatement("SELECT * from bookings INNER JOIN listings ON listings.list_id = bookings.listings_list_id");
            ResultSet rs = ps.executeQuery();
            System.out.println("listing search works");
            model.setRowCount(1);
            int rowIndex = 0;
            while (rs.next() && rowIndex < model.getRowCount()) {
 
                model.insertRow(rowIndex, 
                        new Object [] {rs.getString("u_id"),rs.getString("cancelled"),
                            rs.getString("list_name"),rs.getString("booking_date")});
                rowIndex++;
            }
          
        } catch (SQLException e) {
            System.out.println("error");
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addListingCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addListingCommentActionPerformed
        
        try {
            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            // setup connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/my_bnb?useSSL=false","root","rootpassword");
         
            // checks whether the renter has rented from the host before
            PreparedStatement ps = conn.prepareStatement("SELECT * from renter_has_listings WHERE listings_list_id=(?)");
            System.out.println("ioegigijerg");
            
            ps.setString(1,commentListId.getText());
            ResultSet rs = ps.executeQuery();
            
            // if renter rented from host then insert comment
            if (rs.next()) {
                System.out.println("found match");
                PreparedStatement addComment = conn.prepareStatement("UPDATE renter_has_listings SET comment=?,rating=? WHERE listings_list_id=(?)");
                addComment.setString(1,listingComment.getText());
                addComment.setString(2,listingRating.getText());
                addComment.setString(3,commentListId.getText());
                
                addComment.executeUpdate();
            }
            else{
                System.out.println("no found match");
            }
            
          
        } catch (SQLException e) {
            System.out.println("error");
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_addListingCommentActionPerformed

    private void viewCommentListingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCommentListingsActionPerformed
        DefaultTableModel model ;
        model = (DefaultTableModel)viewBookingTable1.getModel();
        model.setRowCount(0);
        try {
            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            // setup connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/my_bnb?useSSL=false","root","rootpassword");
         
   
            PreparedStatement ps = conn.prepareStatement("SELECT * from listings INNER JOIN bookings ON listings.list_id = bookings.listings_list_id");
            ResultSet rs = ps.executeQuery();
            System.out.println("listing search works");
            model.setRowCount(1);
            int rowIndex = 0;
            while (rs.next() && rowIndex < model.getRowCount()) {
                System.out.println("aioroiaerjg");
                model.insertRow(rowIndex, 
                        new Object [] {rs.getString("u_id"),rs.getString("booking_date"),
                            rs.getString("listings_list_id"),rs.getString("list_name")});
                rowIndex++;
            }
          
        } catch (SQLException e) {
            System.out.println("error");
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_viewCommentListingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RenterProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RenterProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RenterProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RenterProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RenterProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addListingComment;
    private javax.swing.JButton bookButton;
    private javax.swing.JTextField bookDate;
    private javax.swing.JPasswordField bookingPassword;
    private javax.swing.JButton cancelBooking;
    private javax.swing.JTextField commentField;
    private javax.swing.JButton commentHost;
    private javax.swing.JTextField commentListId;
    private javax.swing.JPasswordField commentListPassword;
    private javax.swing.JTextField dateField;
    private javax.swing.JTextField hostComment;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jField12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField listField;
    private javax.swing.JTextField listingComment;
    private javax.swing.JTextField listingField;
    private javax.swing.JTextField listingRating;
    private javax.swing.JTextField listingUserId;
    private javax.swing.JTabbedPane renterBooking;
    private javax.swing.JTable renterTable;
    private javax.swing.JTextField successField;
    private javax.swing.JScrollPane tableDisplay10;
    private javax.swing.JScrollPane tableDisplay11;
    private javax.swing.JScrollPane tableDisplay8;
    private javax.swing.JScrollPane tableDisplay9;
    private javax.swing.JTextField userComment;
    private javax.swing.JTextField userField;
    private javax.swing.JTextField userIdField;
    private javax.swing.JPasswordField userPassComment;
    private javax.swing.JPasswordField userPassword;
    private javax.swing.JTable viewBookingTable;
    private javax.swing.JTable viewBookingTable1;
    private javax.swing.JButton viewCommentListings;
    private javax.swing.JButton viewListings;
    private javax.swing.JButton viewListingsCurrent;
    private javax.swing.JTable viewTableComment;
    // End of variables declaration//GEN-END:variables
}
